### ISSUE TITLE
The program doesn't start uploading

### ISSUE THREAD

**Issue by Nashikk** [nekiak/discordclipuploader#5]
I select a video file, in mp4 if it changes anything (i don't have mkv to try it out), press upload and the button just get's a little more lighter in collor and nothing happens after
![Screenshot_1](https://github.com/nekiak/discordclipuploader/assets/141280387/a6a37e68-7cac-43c4-9ac1-bfe3ebf025f1)

**Comment by olli1616** [comment]
I believe this is because FileDitch, the third party website it depends on, shut down form all the traffic.

**Comment by LeadRR** [comment]
> adapters.py", line 519, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='up1.fileditch.com', port=443): Max retries exceeded with url: /upload.php (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000253121D4490>: Failed to establish a new connection: [WinError 10061] **No connection could be made because the target machine actively refused it**'))

**Comment by nekiak** [comment]
moved to a different website, this one shouldn't have any problems
